### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sabanonitsuke** [sabanonitsuke/protospace-38985#1]
https://protospace-38985.onrender.com/

**Comment by soll02solglas** [comment]
@sabanonitsuke さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
